version: "3.9"

services:

  weather-frontend:
    image: nginx:alpine
    container_name: weather-frontend-container
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:z
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:z

  weather-postgres:
    container_name: weather-postgres-container
    image: "postgres:16-alpine"
    ports:
      - "${POSTGRES_OUTER_PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:z